name: 'Update password action'
author: 'https://github.com/magicnana999'
description: 'Update password with Secret in Action'
inputs:
  dest:
    description: 'Target directory'
    required: true
    default: '**/application.yaml'
  pairs:
    description: 'Pairs of [key:secret]'
    required: true
    default: 'database_name:${{ secrets.DATABASE_TEST }};redis_name:${{ secrets.REDIS_TEST }}'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'terminal'
  color: 'gray-dark'